name: "Poke trigger for static content"

on:
  push:
    branches: ["main", "dev"]
  workflow_dispatch:
  schedule:
    - cron: "* */2 * * 0"

jobs:
  Poke:
    name: Poke
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Node version
        run: node -v
      - name: Remove dependencies
        run: rm -rf package.json package-lock.json
      - name: Install dependencies
        # run: npm ci
        run: npm install node-fetch
      - name: Poke Trigger
        run: node src/trigger/update-static-content.js
