name: "Poke trigger for static content"

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "* */2 * * 0"

jobs:
  Poke:
    name: Poke
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Poke Trigger
        run: node src/trigger/poke.js
